sudo: required
dist: trusty

before_install:
  - sudo integration-scripts/install_repositories.sh
install:
  - sudo integration-scripts/install_common.sh
  - travis_wait 30 sudo integration-scripts/install_codeface_R.sh
  - sudo integration-scripts/install_codeface_python.sh
  - sudo integration-scripts/install_cppstats.sh
  - sudo integration-scripts/setup_database.sh
  - integration-scripts/install_codeface_node.sh
script:
  - integration-scripts/test_codeface.sh

env:
  global:
   - secure: "XB9TCCXMmbRfi6HpTx0Gv4+exASy/E2jAAo2nAMghnnCeIpIpJH/0CKvPlhMrQUSC/2bZMu2QmDsaRhr+JikXWB6IZYtx2h0K9UvETxBckIplkj47SsHRT1fyQQ18qoqa0ctQHzBHh+Vl+S7Dws0ASFWOm1xKN3B6su7D8aJOlc="

addons:
  coverity_scan:
    project:
      name: "siemens/codeface"
      description: "Build submitted via Travis CI"
    notification_email: wolfgang.mauerer@oth-regensburg.de
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: coverity_scan